---
- hosts: wordpressmachines
  tasks:
    - name: Move wordpress 000-default.conf
      become: yes
      command: mv /wordpress/000-default.conf /etc/apache2/sites-enabled/
    - name: Move wordpress
      become: yes
      command: mv /wordpress /var/www/
    - name: remove wp-config
      become: yes
      command: rm -rf /var/www/wordpress/wp-config.php      
