---
    - hosts: wordpressmachines
      tasks:
        - name: Install update
          become: yes
          apt:
            update_cache: true
            cache_valid_time: 3600
            force_apt_get: true
        - name: Install apache
          become: yes
          apt: 
            name: apache2
            state: latest
            update_cache: true
        - name: Install libapache2-mod-php
          become: yes
          apt: 
            name: libapache2-mod-php
            state: latest
            update_cache: true
        - name: install  php-mysql
          become: yes
          apt: 
            name: php-mysql
            state: latest
            update_cache: true